---
version: '2'
services:
  nginx:
    image: nginx:1.10
    ports:
      - 80:80
      - 443:443
    volumes:
       - ./conf/nginx:/etc/nginx/conf.d/:ro
       - ./certs/nginx:/certs:ro
    networks:
      - registry-net
    depends_on:
      - registry
      - registry-web

  registry-web:
    image: hyper/docker-registry-web:latest
    ports:
      - 127.0.0.1:8080:8080
    volumes:
       - ./conf/registry-web:/conf:ro
       - ./certs/registry:/certs:ro
       - registry_web_data:/data
    networks:
      - registry-net
    depends_on:
      - registry

  registry:
    image: registry:2.6
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./conf/registry:/etc/docker/registry:ro
      - ./certs/registry:/certs:ro
      - registry_data:/var/lib/registry
    networks:
      - registry-net


volumes:
  registry_data:
  registry_web_data:

networks:
  registry-net:
